
# Wall resistance tiers
WALL_RESISTANCE_TIER_1: int = 1
WALL_RESISTANCE_TIER_2: int = 2
WALL_RESISTANCE_TIER_3: int = 3
WALL_RESISTANCE_TIER_4: int = 4
WALL_RESISTANCE_TIER_5: int = 5

# Wall durability tiers
WALL_DURABILITY_TIER_1: float = 1.00
WALL_DURABILITY_TIER_2: float = 0.50
WALL_DURABILITY_TIER_3: float = 0.25
WALL_DURABILITY_TIER_4: float = 0.10
WALL_DURABILITY_TIER_5: float = 0.05
